stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules

build_dev:
  image: node:14.17.4-alpine
  stage: build
  only:
    - dev
  environment:
    name: Development
    url: https://dev.querydeck.io
  before_script:
    - apk add zip
  script:
    - npm install
    - npm run build
    - mv public _public
    - mv build public
    - cp public/index.html public/404.html
    - zip -r public.zip public
  artifacts:
    paths:
      - public.zip

build_prod:
  image: node:14.17.4-alpine
  stage: build
  only:
    - main
  environment:
    name: Production
    url: https://app.querydeck.io
  before_script:
    - apk add zip
  script:
    - npm install
    - npm run build
    - mv public _public
    - mv build public
    - cp public/index.html public/404.html
    - zip -r public.zip public
  artifacts:
    paths:
      - public.zip

# test_prod:
#   image: node:14.17.4-alpine
#   stage: test
#   only:
#     - main
#   environment:
#     name: Production
#     url: https://app.querydeck.io
#   before_script:
#     - echo -n "Jest testing starting..."
#   script:
#     - npm install
#     - npm test

deploy_dev:
  image: node:14.17.4-alpine
  stage: deploy
  only:
    - dev
  environment:
    name: Development
    url: https://dev.querydeck.io
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEV_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $DEV_SERVER_ADDRESS "cd /var/www/dev.querydeck.io/html; pm2 stop 'Deck Dev'; rm -rf public"
    - scp -o StrictHostKeyChecking=no public.zip $DEV_SERVER_ADDRESS:/var/www/dev.querydeck.io/html
    - ssh -o StrictHostKeyChecking=no $DEV_SERVER_ADDRESS "cd /var/www/dev.querydeck.io/html; unzip public.zip; rm public.zip; pm2 start 'Deck Dev'"

deploy_prod:
  image: node:14.17.4-alpine
  stage: deploy
  only:
    - main
  environment:
    name: Production
    url: https://app.querydeck.io
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$MAIN_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $MAIN_SERVER_ADDRESS "cd /var/www/app.querydeck.io/html; pm2 stop App; rm -rf public"
    - scp -o StrictHostKeyChecking=no public.zip $MAIN_SERVER_ADDRESS:/var/www/app.querydeck.io/html
    - ssh -o StrictHostKeyChecking=no $MAIN_SERVER_ADDRESS "cd /var/www/app.querydeck.io/html; unzip public.zip; rm public.zip; pm2 start App"