FROM node:16.16.0-alpine

WORKDIR /app/backend

RUN npm install -g  nodemon

# copy important files used for npm install 
COPY ./package.json /app/backend/package.json
COPY ./package-lock.json /app/backend/package-lock.json
RUN npm install

# copy the rest of the code
ADD . /app/backend


ENV PORT=3000

EXPOSE 3000
CMD ["npm", "run" , "dc"]