module.exports = {
  REACT_APP_MUI_KEY: process.env.REACT_APP_MUI_KEY,
  REACT_APP_OPENREPLAY_KEY: process.env.REACT_APP_OPENREPLAY_KEY,
  REACT_APP_PUBLIC_POSTHOG_KEY: process.env.REACT_APP_PUBLIC_POSTHOG_KEY,
  REACT_APP_PUBLIC_POSTHOG_HOST: process.env.REACT_APP_PUBLIC_POSTHOG_HOST
}